

oops:
  val: false
  fails_path: '/BS/unintentional_actions/nobackup/oops/oops_dataset/oops_video'
  fails_only: true
  workers: 32
  all_fail_videos: false
  cache_dataset: true
  fails_action_split: false
  balance_fails_only: false
  fps_list:
    - 16
  step_between_clips_sec: 1.0
  anticipate_label: 0
  remove_fns: 'None'
  sample_all_clips: true
  clips_per_video: 10
  kinetics_path: '/BS/unintentional_actions/nobackup/kinetics400/data'
  frames_per_clip: 16
  clip_interval_factor: 1
  dataset_path: '/BS/unintentional_actions/nobackup/oops'
  local_rank: -1
  sample_videos: false
  selfsup_loss: 'None'
  load_videos: true
general:
  model_name: 'VideoLongformer_MLP'
  sfx: ''
  pfx: ''
  crt_weight_training: false
  gpu_parallel: true
  backbone_lr_factor: 1
  cos_decay_lr_factor: 0.01
  pretrained: true
longformer:
  embed_dim: 768
  max_positions_embedding: 7200
  num_attention_heads: 16
  num_hidden_layers: 3
  attention_mode: 'sliding_chunks'
  pad_token_id: -1
  attention_window:
    - 4
    - 4
    - 4
  intermediate_size: 3072
  attention_probs_dropout_prob: 0.1
  hidden_dropout_prob: 0.1
  hidden_dim: 768
  mlp_dropout: 0.2
  mlp_dim: 1024
  num_classes: 3
  num_classes_ptr: 7
  vtn_ptr_path: '/BS/unintentional_actions/work/storage/models/all/VideoLongformer/all.rep_learning.tag:speed&motion.layers3.attn_win4.classes8.time20211104-165437/val/top1/VideoLongformer__all.rep_learning.tag:speed&motion.layers3.attn_win4.classes8.time20211104-165437_v0.5581_ep47.pth.tar'
  use_crf: true
  spat_temp: false
  multi_scale: true
representation_learning:
  rep_data_level: 'features'
  rep_backbone: 'vit'
  speed_and_motion: true
  tag: 'speed&motion'
  transformation_groups: 'speed&motion'
train:
  test: true
  save_model: 1
  test_val: true
  epochs: 50
  use_tqdm: true
  contrastive_loss: false
  rep_learning: true
  optim: 'adam'
  lr: 0.0001
  weight_decay: 0.0001
  test_freq: 1
  dataset: 'oops'
  num_workers: 32
  batch_size: 16
vizdom:
  viz: false

